version: '3.5'
services:
  graphql_gateway:
    image: node:10-alpine
    env_file: .env
    volumes:
      - '.:/app'
    working_dir: /app
    ports:
      - '4000:4000'
    command: sh -c "yarn && yarn start"